name: Unit tests

on:
  push:
    paths:
    - 'flake.lock'
    - 'pkgs/build-support/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run: nix flake update
      working-directory: pkgs/build-support/elisp

    - name: Run unit tests
      run: |
        set -euo pipefail
        nix-instantiate --strict --eval --json pkgs/build-support/**/test*.nix \
        | jq
