name: Convert the document

on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs: ${{ steps.changes.outputs.doc }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          doc:
            - 'doc/*.org'

  build:
    needs: changes
    if: ${{ needs.changes.outputs == 'true' }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: akirak
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        extraPullNames: emacs-ci
        pushFilter: '(-source$|nixpkgs\.tar\.gz$|-generate-info$)'

    - run: nix run .#generate-info
      working-directory: doc

    - run: git diff-index --exit-code --name-status HEAD -- doc
      id: diff
      continue-on-error: true

    - name: Create a pull request
      uses: peter-evans/create-pull-request@v4.0.1
      if: ${{ steps.diff.outcome == 'failure' }}
      with:
        commit-message: 'Re-generate info documentation'
        base: master
        title: 'Re-generate the info version of the manual'
        branch: create-pull-request/doc
        delete-branch: true
        labels: automation
